version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvec
    environment:
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: whatsapp_profiles
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data: